### ISSUE TITLE
XY/model x-derivation step size to large

### ISSUE THREAD

**Issue by cverstege** [PhiLFitters/kafe2#180]
In https://github.com/dsavoiu/kafe2/commit/3eb210812dd0b867e2fab26b23ff5414bd84a4f9 I reduced the derivation step size for the TP1 Geant exercise in order to avoid inf, as `ln(x)` is undefined at 0, which then causes problems with some undefined behaviour in numpy and the cholesky decomposition.
Normally an error would be raised an a value of None returned by: https://github.com/dsavoiu/kafe2/blob/1b683f5562287974332e4e004968e31df8e04d3e/kafe2/fit/util/__init__.py#L44-L54
But for me just a matrix with some elements being `NaN` was returned. Dsavoiu testet this with the same numpy version and an error was raised (as it should be). So this might also be some undefined behaviour upstream in numpy.

Kafe2 right now defaults to a step size of 1 in the derivation in https://github.com/dsavoiu/kafe2/blob/1b683f5562287974332e4e004968e31df8e04d3e/kafe2/fit/xy/model.py#L166 but this should be relative to the x errors or the scale of the x data points. To avoid runnin into undefined x values for the model function.
Ideally the derivation shouldn't be computed at all when it's not needed (e.g. when there are no x-errors given).

**Comment by JohannesGaessler** [comment]
What I think the problem was: the step size is being calculated as 0.01 * x_error .
If x_error contains 0 values the step size is instead set to 1.
I've changed the logic to instead use the default step size that is used if dx is left as None on a value-per-value basis, see https://github.com/PhiLFitters/kafe2/commit/787f03927a07c9a573818ff7db7ca3bb7637e9da .
Please test if this fixes the issue.

**Comment by cverstege** [comment]
Confirmed as fixed. The TP1 Geant exercise can now use the latest kafe2 version again instead of the special version.
