### ISSUE TITLE
Bug: relative uncertainties in kafe2go

### ISSUE THREAD

**Issue by GuenterQuast** [PhiLFitters/kafe2#202]
label: 'Test Data'
Here is a simple example of an input file for kafe2g, which works perfectly:
```
x_data: [.05,0.36,0.68,0.80,1.09,1.46,1.71,1.83,2.44,2.09,3.72,4.36,4.60]
x_errors: 3%
x_label: 'x values'

y_data: [0.35,0.26,0.52,0.44,0.48,0.55,0.66,0.48,0.75,0.70,0.75,0.80,0.90]
y_errors: [.06,.07,.05,.05,.07,.07,.09,.1,.11,.1,.11,.12,.1]
y_label: 'y values'

model_label: 'Parabolic Fit'
model_function: |
  def quadratic_model(x, a=0., b=1., c=0. ):
      # simple quadratic function
      return a * x*x + b*x + c
```
If I replace the line `x_errors: 3%`
by `x_errors: [3%,3%,3%,3%,3%,3%,3%,3%,3%,3%,3%,3%,3%]`
which should  be perfectly equivalent, the x-uncertainties become too large.

**Comment by cverstege** [comment]
Should be fixed on the current dev branch

**Comment by cverstege** [comment]
The issue was, that each relative uncertainty was added on top of the already existing uncertainty, so in the end there was a 13*3% uncertainty. Now it should also be possible to mix and match absolute and relative uncertainties inside a list.
All uncertainties with a % are treated as relative, all without % are treated as asolute.

**Comment by JohannesGaessler** [comment]
I'm closing this issue since it seems to be resolved.
Reopen if necessary.
